import StrategicLocalGreenPolicyCompetition.GovernmentPolicySlopes
import StrategicLocalGreenPolicyCompetition.Proposition2Theta
import StrategicLocalGreenPolicyCompetition.Threshold

noncomputable section

open Set

namespace SLGPC

set_option maxRecDepth 100000

/-- Canonical reduced firm-stage coefficient `L` at the manuscript witness vector. -/
def canonicalL (θ : ℝ) : ℝ :=
  reducedL 4 18 (9 / 10 : ℝ) θ

/-- Polynomial numerator of the canonical reduced two-firm determinant. -/
def canonicalReducedDetNumerator (θ : ℝ) : ℝ :=
  (341 - 100 * θ ^ 2) ^ 2 - 2500 * θ ^ 2 * cournotD θ ^ 2

/-- The common squared denominator factor appearing in the canonical Hessian. -/
def canonicalSlopeCore (θ : ℝ) : ℝ :=
  canonicalReducedDetNumerator θ ^ 2

/-- Canonical Stage-1 Hessian entry inherited from the Phase-6 government bridge. -/
def canonicalGovernmentHessianEntry (θ : ℝ) (i j : PolicyCoord) : ℝ :=
  modelGovernmentHessianEntry 4 18 (9 / 10 : ℝ) (6 / 5 : ℝ)
    (4 / 5 : ℝ) 2 (11 / 10 : ℝ) (17 / 10 : ℝ) (1 / 10 : ℝ)
    (canonicalL θ) θ i j

/-- Canonical numerator of the infrastructure response to the rival subsidy. -/
def canonicalCrossInstrumentNumerator (θ : ℝ) : ℝ :=
  crossInstrumentNumerator
    (canonicalGovernmentHessianEntry θ .sA .hA)
    (canonicalGovernmentHessianEntry θ .sA .sA)
    (canonicalGovernmentHessianEntry θ .sA .sB)
    (canonicalGovernmentHessianEntry θ .hA .sB)

/-- Canonical determinant of jurisdiction A's own-policy Hessian block. -/
def canonicalOwnPolicyDet (θ : ℝ) : ℝ :=
  ownPolicyDet
    (canonicalGovernmentHessianEntry θ .sA .sA)
    (canonicalGovernmentHessianEntry θ .sA .hA)
    (canonicalGovernmentHessianEntry θ .hA .hA)

/-- Positive denominator polynomial in `u = θ²` generated by the own-policy
Hessian determinant at the canonical witness vector. -/
def witnessDetQ (u : ℝ) : ℝ :=
  2423000000 * u ^ 6 - 48022162500 * u ^ 5 +
    380092203500 * u ^ 4 - 1513626514600 * u ^ 3 +
    3201289907783 * u ^ 2 - 3575406211544 * u +
    1926730587848

/-- Integer-scaled Bernstein representation of the determinant polynomial. -/
def witnessDetQBernsteinScaled (u : ℝ) : ℝ :=
  28900958817720 * (1 - u) ^ 6 +
    119774659733160 * u * (1 - u) ^ 5 +
    213378265016745 * u ^ 2 * (1 - u) ^ 4 +
    211081241370780 * u ^ 3 * (1 - u) ^ 3 +
    122907732130170 * u ^ 4 * (1 - u) ^ 2 +
    39896922018000 * u ^ 5 * (1 - u) +
    5602212157305 * u ^ 6

lemma witnessDetQ_scaled_eq_bernstein (u : ℝ) :
    15 * witnessDetQ u = witnessDetQBernsteinScaled u := by
  unfold witnessDetQ witnessDetQBernsteinScaled
  ring

/-- The Hessian-determinant polynomial is strictly positive on the entire rivalry
square range `u ∈ [0,1]`. -/
theorem witnessDetQ_pos {u : ℝ} (hu : u ∈ Icc (0 : ℝ) 1) :
    0 < witnessDetQ u := by
  rcases hu with ⟨hu0, hu1⟩
  by_cases h1 : u = 1
  · subst u
    norm_num [witnessDetQ]
  · have huLt : u < 1 := lt_of_le_of_ne hu1 h1
    have h1u : 0 < 1 - u := by linarith
    have h0 : 0 < 28900958817720 * (1 - u) ^ 6 := by positivity
    have hA : 0 ≤ 119774659733160 * u * (1 - u) ^ 5 := by positivity
    have hB : 0 ≤ 213378265016745 * u ^ 2 * (1 - u) ^ 4 := by positivity
    have hC : 0 ≤ 211081241370780 * u ^ 3 * (1 - u) ^ 3 := by positivity
    have hD : 0 ≤ 122907732130170 * u ^ 4 * (1 - u) ^ 2 := by positivity
    have hE : 0 ≤ 39896922018000 * u ^ 5 * (1 - u) := by positivity
    have hF : 0 ≤ 5602212157305 * u ^ 6 := by positivity
    have hscaled : 0 < 15 * witnessDetQ u := by
      rw [witnessDetQ_scaled_eq_bernstein]
      unfold witnessDetQBernsteinScaled
      nlinarith
    nlinarith

lemma canonicalDetFactor_left_pos {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    0 < 50 * θ ^ 3 - 100 * θ ^ 2 - 200 * θ + 341 := by
  have hsq : θ ^ 2 ≤ 1 := by
    nlinarith [mul_nonneg hθ.1 (sub_nonneg.mpr hθ.2)]
  have hcub : 0 ≤ θ ^ 3 := pow_nonneg hθ.1 3
  nlinarith

lemma canonicalDetFactor_right_neg {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    50 * θ ^ 3 + 100 * θ ^ 2 - 200 * θ - 341 < 0 := by
  have hsq : θ ^ 2 ≤ 1 := by
    nlinarith [mul_nonneg hθ.1 (sub_nonneg.mpr hθ.2)]
  have hcub_le : θ ^ 3 ≤ 1 := by
    have hnonneg : 0 ≤ θ ^ 2 * (1 - θ) :=
      mul_nonneg (sq_nonneg θ) (sub_nonneg.mpr hθ.2)
    nlinarith
  nlinarith [hθ.1]

lemma canonicalReducedDetNumerator_factor (θ : ℝ) :
    canonicalReducedDetNumerator θ =
      -(50 * θ ^ 3 - 100 * θ ^ 2 - 200 * θ + 341) *
        (50 * θ ^ 3 + 100 * θ ^ 2 - 200 * θ - 341) := by
  unfold canonicalReducedDetNumerator cournotD
  ring

lemma canonicalReducedDetNumerator_pos {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    0 < canonicalReducedDetNumerator θ := by
  rw [canonicalReducedDetNumerator_factor]
  exact mul_pos_of_neg_of_neg
    (neg_neg_of_pos (canonicalDetFactor_left_pos hθ))
    (canonicalDetFactor_right_neg hθ)

lemma canonicalSlopeCore_pos {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    0 < canonicalSlopeCore θ := by
  unfold canonicalSlopeCore
  exact sq_pos_of_pos (canonicalReducedDetNumerator_pos hθ)

lemma canonicalL_closed {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    canonicalL θ = (341 - 100 * θ ^ 2) / (50 * cournotD θ) := by
  have hD : cournotD θ ≠ 0 := (cournotD_pos hθ).ne'
  unfold canonicalL reducedL investmentLambda investmentR
  field_simp [hD]
  unfold cournotD
  ring

lemma canonicalT0_closed {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    reducedT0 (canonicalL θ) θ =
      50 * cournotD θ * (341 - 100 * θ ^ 2) /
        canonicalReducedDetNumerator θ := by
  have hD : cournotD θ ≠ 0 := (cournotD_pos hθ).ne'
  have hA : canonicalReducedDetNumerator θ ≠ 0 :=
    (canonicalReducedDetNumerator_pos hθ).ne'
  rw [canonicalL_closed hθ]
  unfold reducedT0 canonicalReducedDetNumerator
  field_simp [hD, hA]
  ring

lemma canonicalT1_closed {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    reducedT1 (canonicalL θ) θ =
      -2500 * θ * cournotD θ ^ 2 / canonicalReducedDetNumerator θ := by
  have hD : cournotD θ ≠ 0 := (cournotD_pos hθ).ne'
  have hA : canonicalReducedDetNumerator θ ≠ 0 :=
    (canonicalReducedDetNumerator_pos hθ).ne'
  rw [canonicalL_closed hθ]
  unfold reducedT1 canonicalReducedDetNumerator
  field_simp [hD, hA]
  ring

lemma canonicalChiX_closed (θ : ℝ) :
    interiorChiX 4 θ = 1 / cournotD θ := by
  unfold interiorChiX
  ring

lemma canonicalChiG_closed (θ : ℝ) :
    interiorChiG 18 (9 / 10 : ℝ) θ = 1 / (5 * cournotD θ) := by
  unfold interiorChiG
  ring

lemma canonicalRho_closed (θ : ℝ) :
    producerRho 4 18 (9 / 10 : ℝ) θ =
      1 - 59 / (25 * cournotD θ ^ 2) := by
  unfold producerRho
  rw [canonicalChiX_closed, canonicalChiG_closed]
  ring

/-- Polynomial numerators for the five Hessian entries needed by the response. -/
def canonicalHssPoly (θ : ℝ) : ℝ :=
  74312500 * θ ^ 12 - 1737628125 * θ ^ 10 + 16311746125 * θ ^ 8 -
    78435270800 * θ ^ 6 + 203312608309 * θ ^ 4 -
    269043732787 * θ ^ 2 + 142288292179

def canonicalHshPoly (θ : ℝ) : ℝ :=
  4250000 * θ ^ 12 + 35400000 * θ ^ 10 - 1462181500 * θ ^ 8 +
    11950610900 * θ ^ 6 - 42728067652 * θ ^ 4 +
    70790521867 * θ ^ 2 - 43708399966

def canonicalHhhPoly (θ : ℝ) : ℝ :=
  51250000 * θ ^ 12 - 1029000000 * θ ^ 10 + 8472940000 * θ ^ 8 -
    36039869000 * θ ^ 6 + 84013880320 * θ ^ 4 -
    106205019880 * θ ^ 2 + 62556038413

def canonicalHsCrossPoly (θ : ℝ) : ℝ :=
  1047500 * θ ^ 8 - 14932000 * θ ^ 6 + 75261010 * θ ^ 4 -
    157644181 * θ ^ 2 + 113547544

def canonicalHhCrossPoly (θ : ℝ) : ℝ :=
  102500 * θ ^ 8 - 1205500 * θ ^ 6 + 5196340 * θ ^ 4 -
    8170549 * θ ^ 2 + 1317283

lemma canonicalHss_closed {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    canonicalGovernmentHessianEntry θ .sA .sA =
      -canonicalHssPoly θ / (162 * canonicalSlopeCore θ) := by
  simp [canonicalGovernmentHessianEntry, modelGovernmentHessianEntry,
    qASlope, qBSlope, ownSubsidySlope, ownInfrastructureSlope]
  rw [canonicalT0_closed hθ, canonicalT1_closed hθ,
    canonicalChiG_closed, canonicalRho_closed]
  unfold governmentHessianEntry reducedEmissionsSlope canonicalSlopeCore
  field_simp [(cournotD_pos hθ).ne', (canonicalReducedDetNumerator_pos hθ).ne']
  unfold canonicalHssPoly canonicalReducedDetNumerator cournotD
  ring

lemma canonicalHsh_closed {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    canonicalGovernmentHessianEntry θ .sA .hA =
      -canonicalHshPoly θ / (36 * canonicalSlopeCore θ) := by
  simp [canonicalGovernmentHessianEntry, modelGovernmentHessianEntry,
    qASlope, qBSlope, ownSubsidySlope, ownInfrastructureSlope]
  rw [canonicalT0_closed hθ, canonicalT1_closed hθ,
    canonicalChiG_closed, canonicalRho_closed]
  unfold governmentHessianEntry reducedEmissionsSlope canonicalSlopeCore
  field_simp [(cournotD_pos hθ).ne', (canonicalReducedDetNumerator_pos hθ).ne']
  unfold canonicalHshPoly canonicalReducedDetNumerator cournotD
  ring

lemma canonicalHhh_closed {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    canonicalGovernmentHessianEntry θ .hA .hA =
      -canonicalHhhPoly θ / (10 * canonicalSlopeCore θ) := by
  simp [canonicalGovernmentHessianEntry, modelGovernmentHessianEntry,
    qASlope, qBSlope, ownSubsidySlope, ownInfrastructureSlope]
  rw [canonicalT0_closed hθ, canonicalT1_closed hθ,
    canonicalChiG_closed, canonicalRho_closed]
  unfold governmentHessianEntry reducedEmissionsSlope canonicalSlopeCore
  field_simp [(cournotD_pos hθ).ne', (canonicalReducedDetNumerator_pos hθ).ne']
  unfold canonicalHhhPoly canonicalReducedDetNumerator cournotD
  ring

lemma canonicalHsCross_closed {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    canonicalGovernmentHessianEntry θ .sA .sB =
      -5 * θ * cournotD θ * canonicalHsCrossPoly θ /
        (72 * canonicalSlopeCore θ) := by
  simp [canonicalGovernmentHessianEntry, modelGovernmentHessianEntry,
    qASlope, qBSlope, ownSubsidySlope, ownInfrastructureSlope]
  rw [canonicalT0_closed hθ, canonicalT1_closed hθ,
    canonicalChiG_closed, canonicalRho_closed]
  unfold governmentHessianEntry reducedEmissionsSlope canonicalSlopeCore
  field_simp [(cournotD_pos hθ).ne', (canonicalReducedDetNumerator_pos hθ).ne']
  unfold canonicalHsCrossPoly canonicalReducedDetNumerator cournotD
  ring

lemma canonicalHhCross_closed {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    canonicalGovernmentHessianEntry θ .hA .sB =
      -5 * θ * cournotD θ * canonicalHhCrossPoly θ /
        (2 * canonicalSlopeCore θ) := by
  simp [canonicalGovernmentHessianEntry, modelGovernmentHessianEntry,
    qASlope, qBSlope, ownSubsidySlope, ownInfrastructureSlope]
  rw [canonicalT0_closed hθ, canonicalT1_closed hθ,
    canonicalChiG_closed, canonicalRho_closed]
  unfold governmentHessianEntry reducedEmissionsSlope canonicalSlopeCore
  field_simp [(cournotD_pos hθ).ne', (canonicalReducedDetNumerator_pos hθ).ne']
  unfold canonicalHhCrossPoly canonicalReducedDetNumerator cournotD
  ring

/-- Exact canonical factorization of the response numerator. -/
theorem canonicalCrossInstrumentNumerator_factorization
    {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    864 * canonicalSlopeCore θ * canonicalCrossInstrumentNumerator θ =
      -25 * θ * cournotD θ * witnessP (θ ^ 2) := by
  have hcore : canonicalSlopeCore θ ≠ 0 := (canonicalSlopeCore_pos hθ).ne'
  unfold canonicalCrossInstrumentNumerator crossInstrumentNumerator
  rw [canonicalHsh_closed hθ, canonicalHss_closed hθ,
      canonicalHsCross_closed hθ, canonicalHhCross_closed hθ]
  unfold canonicalHssPoly canonicalHshPoly canonicalHsCrossPoly
    canonicalHhCrossPoly witnessP
  field_simp [hcore]
  unfold canonicalSlopeCore canonicalReducedDetNumerator cournotD
  ring

/-- Exact canonical factorization of the own-policy Hessian determinant. -/
theorem canonicalOwnPolicyDet_factorization
    {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    6480 * canonicalSlopeCore θ * canonicalOwnPolicyDet θ =
      witnessDetQ (θ ^ 2) := by
  have hcore : canonicalSlopeCore θ ≠ 0 := (canonicalSlopeCore_pos hθ).ne'
  unfold canonicalOwnPolicyDet ownPolicyDet
  rw [canonicalHss_closed hθ, canonicalHsh_closed hθ, canonicalHhh_closed hθ]
  unfold canonicalHssPoly canonicalHshPoly canonicalHhhPoly witnessDetQ
  field_simp [hcore]
  unfold canonicalSlopeCore canonicalReducedDetNumerator cournotD
  ring

lemma canonicalCrossInstrumentNumerator_closed
    {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    canonicalCrossInstrumentNumerator θ =
      (-25 * θ * cournotD θ * witnessP (θ ^ 2)) /
        (864 * canonicalSlopeCore θ) := by
  have hden : 864 * canonicalSlopeCore θ ≠ 0 :=
    mul_ne_zero (by norm_num) (canonicalSlopeCore_pos hθ).ne'
  apply (eq_div_iff hden).2
  calc
    canonicalCrossInstrumentNumerator θ * (864 * canonicalSlopeCore θ) =
        864 * canonicalSlopeCore θ * canonicalCrossInstrumentNumerator θ := by ring
    _ = -25 * θ * cournotD θ * witnessP (θ ^ 2) :=
      canonicalCrossInstrumentNumerator_factorization hθ

lemma canonicalOwnPolicyDet_closed
    {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    canonicalOwnPolicyDet θ =
      witnessDetQ (θ ^ 2) / (6480 * canonicalSlopeCore θ) := by
  have hden : 6480 * canonicalSlopeCore θ ≠ 0 :=
    mul_ne_zero (by norm_num) (canonicalSlopeCore_pos hθ).ne'
  apply (eq_div_iff hden).2
  calc
    canonicalOwnPolicyDet θ * (6480 * canonicalSlopeCore θ) =
        6480 * canonicalSlopeCore θ * canonicalOwnPolicyDet θ := by ring
    _ = witnessDetQ (θ ^ 2) := canonicalOwnPolicyDet_factorization hθ

/-- Positive factor multiplying the canonical switching polynomial in the
2x2 differentiated-FOC response algebra. -/
def canonicalOmega (θ : ℝ) : ℝ :=
  375 * θ * cournotD θ / (2 * witnessDetQ (θ ^ 2))

theorem canonicalOmega_pos {θ : ℝ} (hθ : θ ∈ Ioc (0 : ℝ) 1) :
    0 < canonicalOmega θ := by
  have hθIcc : θ ∈ Icc (0 : ℝ) 1 := ⟨hθ.1.le, hθ.2⟩
  have hD : 0 < cournotD θ := cournotD_pos hθIcc
  have hsq : θ ^ 2 ∈ Icc (0 : ℝ) 1 := by
    constructor
    · exact sq_nonneg θ
    · have hp : 0 ≤ (1 - θ) * (1 + θ) :=
        mul_nonneg (sub_nonneg.mpr hθ.2) (by linarith [hθ.1])
      nlinarith
  have hQ : 0 < witnessDetQ (θ ^ 2) := witnessDetQ_pos hsq
  unfold canonicalOmega
  exact div_pos (mul_pos (mul_pos (by norm_num) hθ.1) hD)
    (mul_pos (by norm_num) hQ)

/-- Canonical infrastructure response expressed directly as the quotient supplied
by the Phase-6 2x2 differentiated-FOC algebra. -/
def canonicalInfrastructureResponse (θ : ℝ) : ℝ :=
  canonicalCrossInstrumentNumerator θ / canonicalOwnPolicyDet θ

/-- Phase 7 closes the model-to-quartic bridge: the canonical response generated by
the Phase-6 Hessian is exactly `-Ω(θ) P(θ²)`. -/
theorem canonicalInfrastructureResponse_eq_thresholdResponse
    {θ : ℝ} (hθ : θ ∈ Ioc (0 : ℝ) 1) :
    canonicalInfrastructureResponse θ =
      -canonicalOmega θ * witnessP (θ ^ 2) := by
  have hθIcc : θ ∈ Icc (0 : ℝ) 1 := ⟨hθ.1.le, hθ.2⟩
  have hcore : canonicalSlopeCore θ ≠ 0 := (canonicalSlopeCore_pos hθIcc).ne'
  have hsq : θ ^ 2 ∈ Icc (0 : ℝ) 1 := by
    constructor
    · exact sq_nonneg θ
    · have hp : 0 ≤ (1 - θ) * (1 + θ) :=
        mul_nonneg (sub_nonneg.mpr hθ.2) (by linarith [hθ.1])
      nlinarith
  have hQ : witnessDetQ (θ ^ 2) ≠ 0 := (witnessDetQ_pos hsq).ne'
  unfold canonicalInfrastructureResponse
  rw [canonicalCrossInstrumentNumerator_closed hθIcc,
      canonicalOwnPolicyDet_closed hθIcc]
  unfold canonicalOmega
  field_simp [hcore, hQ]
  ring

lemma witnessP_eq_thresholdQuartic (u : ℝ) :
    witnessP u =
      thresholdQuartic 602500 (-8101550) 39588109 (-74143042) 31863144 u := by
  unfold witnessP thresholdQuartic
  ring

/-- The generic Phase-2 response object specializes exactly to the Phase-7 canonical
response on the economically relevant positive-rivalry range. -/
theorem canonicalInfrastructureResponse_eq_generic_thresholdResponse
    {θ : ℝ} (hθ : θ ∈ Ioc (0 : ℝ) 1) :
    canonicalInfrastructureResponse θ =
      thresholdResponse canonicalOmega 602500 (-8101550) 39588109
        (-74143042) 31863144 θ := by
  rw [canonicalInfrastructureResponse_eq_thresholdResponse hθ]
  unfold thresholdResponse
  rw [← witnessP_eq_thresholdQuartic]

/-- End-to-end canonical sign-switch certificate obtained by feeding the Phase-7
Hessian factorization into the generic Phase-2 theorem. -/
theorem canonicalInfrastructureResponse_unique_switch :
    ∃ θStar ∈ Ioo (0 : ℝ) 1,
      witnessP (θStar ^ 2) = 0 ∧
      (∀ θ ∈ Ioo (0 : ℝ) θStar, canonicalInfrastructureResponse θ < 0) ∧
      (∀ θ ∈ Ioc θStar (1 : ℝ), 0 < canonicalInfrastructureResponse θ) := by
  have hgeneric := thresholdResponse_unique_switch
    canonicalOmega
    (A4 := (602500 : ℝ)) (A3 := (-8101550 : ℝ))
    (A2 := (39588109 : ℝ)) (A1 := (-74143042 : ℝ))
    (A0 := (31863144 : ℝ))
    (by norm_num [thresholdQuartic])
    (by norm_num [thresholdQuartic])
    (by norm_num [thresholdB0])
    (by norm_num [thresholdB1])
    (by norm_num [thresholdB2])
    (by norm_num [thresholdB3])
    (by intro θ hθ; exact canonicalOmega_pos hθ)
  rcases hgeneric with ⟨θStar, hθStar, hroot, hbelow, habove⟩
  refine ⟨θStar, hθStar, ?_, ?_, ?_⟩
  · rw [witnessP_eq_thresholdQuartic]
    exact hroot
  · intro θ hθ
    rw [canonicalInfrastructureResponse_eq_generic_thresholdResponse
      ⟨hθ.1, le_trans hθ.2.le hθStar.2.le⟩]
    exact hbelow θ hθ
  · intro θ hθ
    rw [canonicalInfrastructureResponse_eq_generic_thresholdResponse
      ⟨lt_trans hθStar.1 hθ.1, hθ.2⟩]
    exact habove θ hθ

end SLGPC
