import StrategicLocalGreenPolicyCompetition.GovernmentPolicySlopes
import StrategicLocalGreenPolicyCompetition.Proposition2Theta

noncomputable section

open Set

namespace SLGPC

/-- Canonical reduced firm-stage coefficient `L` at the manuscript witness vector. -/
def canonicalL (θ : ℝ) : ℝ :=
  reducedL 4 18 (9 / 10 : ℝ) θ

/-- Canonical Stage-1 Hessian entry inherited from the Phase-6 government bridge. -/
def canonicalGovernmentHessianEntry (θ : ℝ) (i j : PolicyCoord) : ℝ :=
  modelGovernmentHessianEntry 4 18 (9 / 10 : ℝ) (6 / 5 : ℝ)
    (4 / 5 : ℝ) 2 (11 / 10 : ℝ) (17 / 10 : ℝ) (1 / 10 : ℝ)
    (canonicalL θ) θ i j

/-- Canonical numerator of the infrastructure response to the rival subsidy. -/
def canonicalCrossInstrumentNumerator (θ : ℝ) : ℝ :=
  crossInstrumentNumerator
    (canonicalGovernmentHessianEntry θ .sA .hA)
    (canonicalGovernmentHessianEntry θ .sA .sA)
    (canonicalGovernmentHessianEntry θ .sA .sB)
    (canonicalGovernmentHessianEntry θ .hA .sB)

/-- Canonical determinant of jurisdiction A's own-policy Hessian block. -/
def canonicalOwnPolicyDet (θ : ℝ) : ℝ :=
  ownPolicyDet
    (canonicalGovernmentHessianEntry θ .sA .sA)
    (canonicalGovernmentHessianEntry θ .sA .hA)
    (canonicalGovernmentHessianEntry θ .hA .hA)

/-- Common squared denominator appearing in the canonical Hessian entries. -/
def canonicalSlopeCore (θ : ℝ) : ℝ :=
  (50 * θ ^ 3 - 100 * θ ^ 2 - 200 * θ + 341) ^ 2 *
    (50 * θ ^ 3 + 100 * θ ^ 2 - 200 * θ - 341) ^ 2

/-- Positive denominator polynomial in `u = θ²` generated by the own-policy
Hessian determinant at the canonical witness vector. -/
def witnessDetQ (u : ℝ) : ℝ :=
  2423000000 * u ^ 6 - 48022162500 * u ^ 5 +
    380092203500 * u ^ 4 - 1513626514600 * u ^ 3 +
    3201289907783 * u ^ 2 - 3575406211544 * u +
    1926730587848

/-- Integer-scaled Bernstein representation of the determinant polynomial. -/
def witnessDetQBernsteinScaled (u : ℝ) : ℝ :=
  28900958817720 * (1 - u) ^ 6 +
    119774659733160 * u * (1 - u) ^ 5 +
    213378265016745 * u ^ 2 * (1 - u) ^ 4 +
    211081241370780 * u ^ 3 * (1 - u) ^ 3 +
    122907732130170 * u ^ 4 * (1 - u) ^ 2 +
    39896922018000 * u ^ 5 * (1 - u) +
    5602212157305 * u ^ 6

lemma witnessDetQ_scaled_eq_bernstein (u : ℝ) :
    15 * witnessDetQ u = witnessDetQBernsteinScaled u := by
  unfold witnessDetQ witnessDetQBernsteinScaled
  ring

/-- The Hessian-determinant polynomial is strictly positive on the entire rivalry
square range `u ∈ [0,1]`. -/
theorem witnessDetQ_pos {u : ℝ} (hu : u ∈ Icc (0 : ℝ) 1) :
    0 < witnessDetQ u := by
  rcases hu with ⟨hu0, hu1⟩
  by_cases h1 : u = 1
  · subst u
    norm_num [witnessDetQ]
  · have huLt : u < 1 := lt_of_le_of_ne hu1 h1
    have h1u : 0 < 1 - u := by linarith
    have h0 : 0 < 28900958817720 * (1 - u) ^ 6 := by positivity
    have hA : 0 ≤ 119774659733160 * u * (1 - u) ^ 5 := by positivity
    have hB : 0 ≤ 213378265016745 * u ^ 2 * (1 - u) ^ 4 := by positivity
    have hC : 0 ≤ 211081241370780 * u ^ 3 * (1 - u) ^ 3 := by positivity
    have hD : 0 ≤ 122907732130170 * u ^ 4 * (1 - u) ^ 2 := by positivity
    have hE : 0 ≤ 39896922018000 * u ^ 5 * (1 - u) := by positivity
    have hF : 0 ≤ 5602212157305 * u ^ 6 := by positivity
    have hscaled : 0 < 15 * witnessDetQ u := by
      rw [witnessDetQ_scaled_eq_bernstein]
      unfold witnessDetQBernsteinScaled
      nlinarith
    nlinarith

lemma canonicalSlopeCore_left_pos {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    0 < 50 * θ ^ 3 - 100 * θ ^ 2 - 200 * θ + 341 := by
  have hsq : θ ^ 2 ≤ 1 := by
    nlinarith [mul_nonneg hθ.1 (sub_nonneg.mpr hθ.2)]
  have hcub : 0 ≤ θ ^ 3 := pow_nonneg hθ.1 3
  nlinarith

lemma canonicalSlopeCore_right_neg {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    50 * θ ^ 3 + 100 * θ ^ 2 - 200 * θ - 341 < 0 := by
  have hsq : θ ^ 2 ≤ 1 := by
    nlinarith [mul_nonneg hθ.1 (sub_nonneg.mpr hθ.2)]
  have hcub_le : θ ^ 3 ≤ 1 := by
    have hnonneg : 0 ≤ θ ^ 2 * (1 - θ) :=
      mul_nonneg (sq_nonneg θ) (sub_nonneg.mpr hθ.2)
    nlinarith
  nlinarith [hθ.1]

lemma canonicalSlopeCore_pos {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    0 < canonicalSlopeCore θ := by
  unfold canonicalSlopeCore
  have hL := canonicalSlopeCore_left_pos hθ
  have hR := canonicalSlopeCore_right_neg hθ
  exact mul_pos (sq_pos_of_pos hL) (sq_pos_of_neg hR)

lemma canonical_reduced_det_ne {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    canonicalL θ ^ 2 - θ ^ 2 ≠ 0 := by
  have hR : investmentR 4 18 (9 / 10 : ℝ) < (3 / 4 : ℝ) := by
    norm_num [investmentR]
  exact (reducedDet_pos hθ hR).ne'

/-- Exact canonical factorization of the response numerator.  The only sign-changing
factor on `(0,1]` is the already-certified quartic `witnessP(θ²)`. -/
theorem canonicalCrossInstrumentNumerator_factorization
    {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    864 * canonicalSlopeCore θ * canonicalCrossInstrumentNumerator θ =
      -25 * θ * cournotD θ * witnessP (θ ^ 2) := by
  have hD : cournotD θ ≠ 0 := (cournotD_pos hθ).ne'
  have hdet : canonicalL θ ^ 2 - θ ^ 2 ≠ 0 := canonical_reduced_det_ne hθ
  unfold canonicalCrossInstrumentNumerator canonicalGovernmentHessianEntry
    modelGovernmentHessianEntry crossInstrumentNumerator governmentHessianEntry
    reducedEmissionsSlope qASlope qBSlope ownSubsidySlope ownInfrastructureSlope
    producerRho interiorChiX interiorChiG canonicalL reducedT0 reducedT1
    reducedL investmentLambda investmentR canonicalSlopeCore witnessP cournotD
  field_simp [hD, hdet]
  ring

/-- Exact canonical factorization of the own-policy Hessian determinant. -/
theorem canonicalOwnPolicyDet_factorization
    {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    6480 * canonicalSlopeCore θ * canonicalOwnPolicyDet θ =
      witnessDetQ (θ ^ 2) := by
  have hD : cournotD θ ≠ 0 := (cournotD_pos hθ).ne'
  have hdet : canonicalL θ ^ 2 - θ ^ 2 ≠ 0 := canonical_reduced_det_ne hθ
  unfold canonicalOwnPolicyDet canonicalGovernmentHessianEntry
    modelGovernmentHessianEntry ownPolicyDet governmentHessianEntry
    reducedEmissionsSlope qASlope qBSlope ownSubsidySlope ownInfrastructureSlope
    producerRho interiorChiX interiorChiG canonicalL reducedT0 reducedT1
    reducedL investmentLambda investmentR canonicalSlopeCore witnessDetQ cournotD
  field_simp [hD, hdet]
  ring

/-- Positive factor multiplying the canonical switching polynomial in the true
2x2 differentiated-FOC response algebra. -/
def canonicalOmega (θ : ℝ) : ℝ :=
  375 * θ * cournotD θ / (2 * witnessDetQ (θ ^ 2))

theorem canonicalOmega_pos {θ : ℝ} (hθ : θ ∈ Ioc (0 : ℝ) 1) :
    0 < canonicalOmega θ := by
  have hθIcc : θ ∈ Icc (0 : ℝ) 1 := ⟨hθ.1.le, hθ.2⟩
  have hD : 0 < cournotD θ := cournotD_pos hθIcc
  have hsq : θ ^ 2 ∈ Icc (0 : ℝ) 1 := by
    constructor
    · exact sq_nonneg θ
    · have hp : 0 ≤ (1 - θ) * (1 + θ) :=
        mul_nonneg (sub_nonneg.mpr hθ.2) (by linarith [hθ.1])
      nlinarith
  have hQ : 0 < witnessDetQ (θ ^ 2) := witnessDetQ_pos hsq
  unfold canonicalOmega
  positivity

/-- Canonical infrastructure response expressed directly as the quotient supplied
by the Phase-6 2x2 differentiated-FOC algebra. -/
def canonicalInfrastructureResponse (θ : ℝ) : ℝ :=
  canonicalCrossInstrumentNumerator θ / canonicalOwnPolicyDet θ

/-- Phase 7 closes the model-to-quartic bridge: the canonical response generated by
the Phase-6 Hessian is exactly `-Ω(θ) P(θ²)`. -/
theorem canonicalInfrastructureResponse_eq_thresholdResponse
    {θ : ℝ} (hθ : θ ∈ Ioc (0 : ℝ) 1) :
    canonicalInfrastructureResponse θ =
      -canonicalOmega θ * witnessP (θ ^ 2) := by
  have hθIcc : θ ∈ Icc (0 : ℝ) 1 := ⟨hθ.1.le, hθ.2⟩
  have hcore : 0 < canonicalSlopeCore θ := canonicalSlopeCore_pos hθIcc
  have hQ : 0 < witnessDetQ (θ ^ 2) := by
    apply witnessDetQ_pos
    constructor
    · exact sq_nonneg θ
    · have hp : 0 ≤ (1 - θ) * (1 + θ) :=
        mul_nonneg (sub_nonneg.mpr hθ.2) (by linarith [hθ.1])
      nlinarith
  have hdetfac := canonicalOwnPolicyDet_factorization hθIcc
  have hnumfac := canonicalCrossInstrumentNumerator_factorization hθIcc
  have hown : canonicalOwnPolicyDet θ ≠ 0 := by
    intro hz
    rw [hz] at hdetfac
    simp at hdetfac
    nlinarith
  unfold canonicalInfrastructureResponse canonicalOmega
  apply (eq_div_iff hown).2
  field_simp [hQ.ne']
  nlinarith [hnumfac, hdetfac]

lemma witnessP_eq_thresholdQuartic (u : ℝ) :
    witnessP u =
      thresholdQuartic 602500 (-8101550) 39588109 (-74143042) 31863144 u := by
  unfold witnessP thresholdQuartic
  ring

/-- The generic Phase-2 response object specializes exactly to the Phase-7 canonical
response on the economically relevant positive-rivalry range. -/
theorem canonicalInfrastructureResponse_eq_generic_thresholdResponse
    {θ : ℝ} (hθ : θ ∈ Ioc (0 : ℝ) 1) :
    canonicalInfrastructureResponse θ =
      thresholdResponse canonicalOmega 602500 (-8101550) 39588109
        (-74143042) 31863144 θ := by
  rw [canonicalInfrastructureResponse_eq_thresholdResponse hθ]
  unfold thresholdResponse
  rw [← witnessP_eq_thresholdQuartic]

/-- End-to-end canonical sign-switch certificate obtained by feeding the Phase-7
primitive/Hessian factorization into the generic Phase-2 theorem. -/
theorem canonicalInfrastructureResponse_unique_switch :
    ∃ θStar ∈ Ioo (0 : ℝ) 1,
      witnessP (θStar ^ 2) = 0 ∧
      (∀ θ ∈ Ioo (0 : ℝ) θStar, canonicalInfrastructureResponse θ < 0) ∧
      (∀ θ ∈ Ioc θStar (1 : ℝ), 0 < canonicalInfrastructureResponse θ) := by
  have hgeneric := thresholdResponse_unique_switch
    canonicalOmega
    (A4 := (602500 : ℝ)) (A3 := (-8101550 : ℝ))
    (A2 := (39588109 : ℝ)) (A1 := (-74143042 : ℝ))
    (A0 := (31863144 : ℝ))
    (by norm_num [thresholdQuartic])
    (by norm_num [thresholdQuartic])
    (by norm_num [thresholdB0])
    (by norm_num [thresholdB1])
    (by norm_num [thresholdB2])
    (by norm_num [thresholdB3])
    (by intro θ hθ; exact canonicalOmega_pos hθ)
  rcases hgeneric with ⟨θStar, hθStar, hroot, hbelow, habove⟩
  refine ⟨θStar, hθStar, ?_, ?_, ?_⟩
  · rw [witnessP_eq_thresholdQuartic]
    exact hroot
  · intro θ hθ
    rw [canonicalInfrastructureResponse_eq_generic_thresholdResponse
      ⟨hθ.1, le_trans hθ.2.le hθStar.2.le⟩]
    exact hbelow θ hθ
  · intro θ hθ
    rw [canonicalInfrastructureResponse_eq_generic_thresholdResponse
      ⟨lt_trans hθStar.1 hθ.1, hθ.2⟩]
    exact habove θ hθ

end SLGPC
