import StrategicLocalGreenPolicyCompetition.GovernmentGlobalOptimality
import StrategicLocalGreenPolicyCompetition.Stage2Endpoint

noncomputable section

open Set

namespace SLGPC

set_option maxRecDepth 100000

local instance (p : Prop) : Decidable p := Classical.propDecidable p

/-- Extensionality for the four-component policy profile. -/
lemma policyProfile_ext
    {z z' : PolicyProfile}
    (hsA : z.sA = z'.sA) (hhA : z.hA = z'.hA)
    (hsB : z.sB = z'.sB) (hhB : z.hB = z'.hB) : z = z' := by
  cases z
  cases z'
  simp_all

/-- Canonical Stage-2 scalar investment coefficient. -/
def canonicalR : ℝ := investmentR 4 18 (9 / 10 : ℝ)

lemma canonicalR_value : canonicalR = 59 / 200 := by
  unfold canonicalR
  exact canonicalInvestmentR

lemma canonicalR_ne : canonicalR ≠ 0 := by
  rw [canonicalR_value]
  norm_num

lemma canonicalM_value : monopolyM canonicalR = 341 / 200 := by
  rw [canonicalR_value]
  norm_num [monopolyM]

/-- Policy profile generated by an arbitrary unilateral A-government deviation
against the canonical symmetric rival policy. -/
def canonicalADeviationProfile (θ s h : ℝ) : PolicyProfile :=
  { sA := s
    hA := h
    sB := canonicalSymmetricS θ
    hB := canonicalSymmetricH θ }

lemma canonicalADeviationProfile_eq_shift (θ s h : ℝ) :
    ownPolicyShift (canonicalSymmetricProfile θ)
        (s - canonicalSymmetricS θ) (h - canonicalSymmetricH θ) =
      canonicalADeviationProfile θ s h := by
  apply policyProfile_ext <;>
    simp [canonicalADeviationProfile, canonicalSymmetricProfile,
      ownPolicyShift, shiftPolicy] <;> ring

lemma canonicalOwnW_pos {s h : ℝ} (hs : 0 ≤ s) (hh : 0 ≤ h) :
    0 < canonicalOwnW s h := by
  unfold canonicalOwnW reducedW policyY
  nlinarith

/-- The five actual downstream regime predicates for an A-government deviation
against the canonical rival. -/
def canonicalAMonopolyRegion (θ s h : ℝ) : Prop :=
  aMonopolyRegion canonicalR θ (canonicalOwnW s h) (canonicalSymmetricW θ)

def canonicalAKinkRegion (θ s h : ℝ) : Prop :=
  aKinkRegion canonicalR (canonicalL θ) θ
    (canonicalOwnW s h) (canonicalSymmetricW θ)

def canonicalDuopolyRegion (θ s h : ℝ) : Prop :=
  duopolyRegion (canonicalL θ) θ
    (canonicalOwnW s h) (canonicalSymmetricW θ)

def canonicalBKinkRegion (θ s h : ℝ) : Prop :=
  bKinkRegion canonicalR (canonicalL θ) θ
    (canonicalOwnW s h) (canonicalSymmetricW θ)

def canonicalBMonopolyRegion (θ s h : ℝ) : Prop :=
  bMonopolyRegion canonicalR θ (canonicalOwnW s h) (canonicalSymmetricW θ)

lemma canonicalDeviation_regions_exhaustive (θ s h : ℝ) :
    canonicalAMonopolyRegion θ s h ∨
    canonicalAKinkRegion θ s h ∨
    canonicalDuopolyRegion θ s h ∨
    canonicalBKinkRegion θ s h ∨
    canonicalBMonopolyRegion θ s h := by
  simpa [canonicalAMonopolyRegion, canonicalAKinkRegion,
    canonicalDuopolyRegion, canonicalBKinkRegion, canonicalBMonopolyRegion,
    canonicalR, canonicalL] using
    (model_stage2_region_exists
      (kx := (4 : ℝ)) (kg := (18 : ℝ)) (μ := (9 / 10 : ℝ))
      (θ := θ) (wA := canonicalOwnW s h) (wB := canonicalSymmetricW θ))

/-- Exact Stage-2 continuation selected by the manuscript's five tie-broken
regimes after a unilateral A-government deviation. -/
def canonicalDeviationContinuation (θ s h : ℝ) : Stage2Continuation :=
  if canonicalAMonopolyRegion θ s h then
    aMonopolyContinuation canonicalR (canonicalOwnW s h)
  else if canonicalAKinkRegion θ s h then
    aKinkContinuation θ (canonicalOwnW s h) (canonicalSymmetricW θ)
  else if canonicalDuopolyRegion θ s h then
    duopolyContinuation (canonicalL θ) θ
      (canonicalOwnW s h) (canonicalSymmetricW θ)
  else if canonicalBKinkRegion θ s h then
    bKinkContinuation θ (canonicalOwnW s h) (canonicalSymmetricW θ)
  else
    bMonopolyContinuation canonicalR (canonicalSymmetricW θ)

/-- Government A's exact branchwise welfare after the selected downstream
continuation.  The active branch uses the already-proved primitive-to-reduced
active government objective; the four corner branches use the common primitive
outside-branch expression. -/
def canonicalGovernmentDeviationWelfare (θ s h : ℝ) : ℝ :=
  if canonicalAMonopolyRegion θ s h then
    canonicalMonopolyGovernmentWelfare θ s h
  else if canonicalAKinkRegion θ s h then
    canonicalKinkGovernmentWelfare θ (canonicalSymmetricW θ) s h
  else if canonicalDuopolyRegion θ s h then
    canonicalActiveGovernmentWelfare θ (canonicalADeviationProfile θ s h)
  else if canonicalBKinkRegion θ s h then
    canonicalOutsideGovernmentWelfare θ 0 (canonicalOwnW s h / θ) 0 s h
  else
    canonicalOutsideGovernmentWelfare θ 0
      (canonicalSymmetricW θ / monopolyM canonicalR) 0 s h

/-- Nonnegative own policies make both rival-dominance regimes impossible.  At
`theta=0` this is the endpoint partition theorem; for positive rivalry it follows
from the Bernstein-certified lower margin and the strict `L<M` ordering. -/
theorem canonical_nonnegative_policy_excludes_B_side
    {θ s h : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) (hs : 0 ≤ s) (hh : 0 ≤ h) :
    ¬ canonicalBKinkRegion θ s h ∧ ¬ canonicalBMonopolyRegion θ s h := by
  have hwA : 0 < canonicalOwnW s h := canonicalOwnW_pos hs hh
  have hwB : 0 < canonicalSymmetricW θ := canonicalSymmetricW_pos hθ
  have hR : canonicalR < (3 / 4 : ℝ) := by
    rw [canonicalR_value]
    norm_num
  by_cases hzero : θ = 0
  · subst θ
    have hz := stage2_theta_zero_no_exclusion
      (kx := (4 : ℝ)) (kg := (18 : ℝ)) (μ := (9 / 10 : ℝ))
      (wA := canonicalOwnW s h) (wB := canonicalSymmetricW 0)
      (by simpa [canonicalR] using hR) hwA hwB
    constructor
    · simpa [canonicalBKinkRegion, canonicalR, canonicalL] using hz.2.2.1
    · simpa [canonicalBMonopolyRegion, canonicalR] using hz.2.2.2
  · have hpos : 0 < θ := lt_of_le_of_ne hθ.1 (Ne.symm hzero)
    have hlower := canonicalLowerSide_inaccessible hθ hs hh
    have hLM : canonicalL θ < monopolyM canonicalR := by
      have h := reducedL_lt_monopolyM
        (kx := (4 : ℝ)) (kg := (18 : ℝ)) (μ := (9 / 10 : ℝ))
        (θ := θ) (by norm_num) (by norm_num) hθ hpos
      simpa [canonicalL, canonicalR] using h
    constructor
    · intro hBK
      have hb : canonicalL θ * canonicalOwnW s h ≤
          θ * canonicalSymmetricW θ := hBK.1
      exact (not_lt_of_ge hb) hlower
    · intro hBM
      have hb : canonicalL θ * canonicalOwnW s h ≤
          θ * canonicalSymmetricW θ :=
        bMonopoly_implies_bSide hLM hwA hBM
      exact (not_lt_of_ge hb) hlower

/-- Exact factorization of the welfare gap between the canonical active equilibrium
and the maximum on the common A-kink/A-monopoly boundary.  The two numerator
factors are the Bernstein-positive certificates in `GovernmentGlobalOptimality`. -/
theorem canonical_equilibrium_boundary_gap_identity
    {θ : ℝ} (hθ : θ ∈ Ioc (0 : ℝ) 1) :
    canonicalActiveGovernmentWelfare θ (canonicalSymmetricProfile θ) -
      canonicalMonopolyGovernmentWelfare θ
        (canonicalBoundaryS θ) (canonicalBoundaryH θ) =
      32 * canonicalGapP6 θ * canonicalGapP14 θ /
        (21358125 * θ ^ 2 * canonicalSymmetricDen θ ^ 2) := by
  have hI : θ ∈ Icc (0 : ℝ) 1 := ⟨hθ.1.le, hθ.2⟩
  have ht : θ ≠ 0 := hθ.1.ne'
  have hD : cournotD θ ≠ 0 := (cournotD_pos hI).ne'
  have hred : canonicalReducedDetNumerator θ ≠ 0 :=
    (canonicalReducedDetNumerator_pos hI).ne'
  have hden : canonicalSymmetricDen θ ≠ 0 :=
    (canonicalSymmetricDen_pos hI).ne'
  have hq0 : canonicalQ0Den θ ≠ 0 := (canonicalQ0Den_pos hI).ne'
  have hq0n := canonicalQ0Den_normalized_ne hI
  unfold canonicalActiveGovernmentWelfare interiorReducedGovernmentPolicyWelfare
    interiorPolicyQA interiorPolicyQB canonicalSymmetricProfile
  simp only
  rw [canonicalT0_closed hI, canonicalT1_closed hI,
    canonicalReducedQ0_closed hI, canonicalChiG_closed, canonicalRho_closed]
  unfold reducedGovernmentWelfare reducedEmissions
    canonicalMonopolyGovernmentWelfare canonicalOutsideGovernmentWelfare
    canonicalOwnW reducedW policyY halfConsumerSurplus
    canonicalBoundaryS canonicalBoundaryH canonicalSymmetricS canonicalSymmetricH
  dsimp
  field_simp [ht, hD, hred, hden, hq0]
  field_simp [hq0n]
  unfold canonicalQ0Den canonicalReducedDetNumerator cournotD
    canonicalBoundarySPos canonicalBoundaryHPos
    canonicalSymmetricDen canonicalSymmetricSNum canonicalSymmetricHNum
    canonicalGapP6 canonicalGapP14
  ring

/-- The canonical active equilibrium strictly dominates the best attainable
welfare on the outside-branch common boundary for every positive rivalry value. -/
theorem canonical_equilibrium_welfare_gt_boundary
    {θ : ℝ} (hθ : θ ∈ Ioc (0 : ℝ) 1) :
    canonicalMonopolyGovernmentWelfare θ
        (canonicalBoundaryS θ) (canonicalBoundaryH θ) <
      canonicalActiveGovernmentWelfare θ (canonicalSymmetricProfile θ) := by
  have hden : 0 < canonicalSymmetricDen θ :=
    canonicalSymmetricDen_pos ⟨hθ.1.le, hθ.2⟩
  have hp6 : 0 < canonicalGapP6 θ := canonicalGapP6_pos hθ
  have hp14 : 0 < canonicalGapP14 θ := canonicalGapP14_pos hθ
  have ht2 : 0 < θ ^ 2 := sq_pos_of_pos hθ.1
  have hd2 : 0 < canonicalSymmetricDen θ ^ 2 := sq_pos_of_pos hden
  have hposden :
      0 < 21358125 * θ ^ 2 * canonicalSymmetricDen θ ^ 2 :=
    mul_pos (mul_pos (by norm_num) ht2) hd2
  have hnum : 0 < 32 * canonicalGapP6 θ * canonicalGapP14 θ :=
    mul_pos (mul_pos (by norm_num) hp6) hp14
  have hgap :
      0 < 32 * canonicalGapP6 θ * canonicalGapP14 θ /
        (21358125 * θ ^ 2 * canonicalSymmetricDen θ ^ 2) :=
    div_pos hnum hposden
  have hid := canonical_equilibrium_boundary_gap_identity hθ
  nlinarith

/-- Cross-regime global government best response against the canonical symmetric
rival.  The quantified deviation is the full nonnegative policy domain and the
welfare function follows the actual five-regime Stage-2 continuation. -/
theorem canonical_government_global_best_response
    {θ s h : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) (hs : 0 ≤ s) (hh : 0 ≤ h) :
    canonicalGovernmentDeviationWelfare θ s h ≤
      canonicalActiveGovernmentWelfare θ (canonicalSymmetricProfile θ) := by
  have hwA : 0 < canonicalOwnW s h := canonicalOwnW_pos hs hh
  have hwB : 0 < canonicalSymmetricW θ := canonicalSymmetricW_pos hθ
  rcases canonical_nonnegative_policy_excludes_B_side hθ hs hh with ⟨hNBK, hNBM⟩
  by_cases hzero : θ = 0
  · subst θ
    have hR : canonicalR < (3 / 4 : ℝ) := by
      rw [canonicalR_value]
      norm_num
    have hz := stage2_theta_zero_certificate
      (kx := (4 : ℝ)) (kg := (18 : ℝ)) (μ := (9 / 10 : ℝ))
      (wA := canonicalOwnW s h) (wB := canonicalSymmetricW 0)
      (by simpa [canonicalR] using hR) hwA hwB
    have hAM : ¬ canonicalAMonopolyRegion 0 s h := by
      simpa [canonicalAMonopolyRegion, canonicalR] using hz.2.1
    have hAK : ¬ canonicalAKinkRegion 0 s h := by
      simpa [canonicalAKinkRegion, canonicalR, canonicalL] using hz.2.2.1
    have hD : canonicalDuopolyRegion 0 s h := by
      simpa [canonicalDuopolyRegion, canonicalL] using hz.1
    simp [canonicalGovernmentDeviationWelfare, hAM, hAK, hD]
    have hbr := canonicalSymmetricProfile_active_best_response
      (θ := (0 : ℝ)) (by constructor <;> norm_num)
      (s - canonicalSymmetricS 0) (h - canonicalSymmetricH 0)
    rw [canonicalADeviationProfile_eq_shift] at hbr
    exact hbr
  · have hpos : θ ∈ Ioc (0 : ℝ) 1 :=
      ⟨lt_of_le_of_ne hθ.1 (Ne.symm hzero), hθ.2⟩
    by_cases hAM : canonicalAMonopolyRegion θ s h
    · simp [canonicalGovernmentDeviationWelfare, hAM]
      have hb := canonicalBoundary_intercept hpos
      have hscaled :
          θ * canonicalOwnW (canonicalBoundaryS θ) (canonicalBoundaryH θ) ≤
            θ * canonicalOwnW s h := by
        calc
          θ * canonicalOwnW (canonicalBoundaryS θ) (canonicalBoundaryH θ) =
              (341 / 200 : ℝ) * canonicalSymmetricW θ := hb
          _ = monopolyM canonicalR * canonicalSymmetricW θ := by
              rw [canonicalM_value]
          _ ≤ θ * canonicalOwnW s h := hAM
      have hside :
          canonicalOwnW (canonicalBoundaryS θ) (canonicalBoundaryH θ) ≤
            canonicalOwnW s h :=
        (mul_le_mul_left hpos.1).mp hscaled
      have hbranch := canonicalMonopoly_branch_le_boundary hpos hside
      have hgap := canonical_equilibrium_welfare_gt_boundary hpos
      exact le_trans hbranch hgap.le
    · by_cases hAK : canonicalAKinkRegion θ s h
      · simp [canonicalGovernmentDeviationWelfare, hAM, hAK]
        have hb := canonicalBoundary_intercept hpos
        have hscaled :
            θ * canonicalOwnW s h <
              θ * canonicalOwnW (canonicalBoundaryS θ) (canonicalBoundaryH θ) := by
          calc
            θ * canonicalOwnW s h <
                monopolyM canonicalR * canonicalSymmetricW θ := hAK.2
            _ = (341 / 200 : ℝ) * canonicalSymmetricW θ := by
                rw [canonicalM_value]
            _ = θ * canonicalOwnW (canonicalBoundaryS θ) (canonicalBoundaryH θ) := hb.symm
        have hside : canonicalOwnW s h ≤
            canonicalOwnW (canonicalBoundaryS θ) (canonicalBoundaryH θ) :=
          ((mul_lt_mul_left hpos.1).mp hscaled).le
        have hk := canonicalKink_branch_le_boundary hpos hside
        have hkm := canonicalBoundary_kink_eq_monopoly hpos
        have hgap := canonical_equilibrium_welfare_gt_boundary hpos
        rw [hkm] at hk
        exact le_trans hk hgap.le
      · by_cases hD : canonicalDuopolyRegion θ s h
        · simp [canonicalGovernmentDeviationWelfare, hAM, hAK, hD]
          have hbr := canonicalSymmetricProfile_active_best_response hθ
            (s - canonicalSymmetricS θ) (h - canonicalSymmetricH θ)
          rw [canonicalADeviationProfile_eq_shift] at hbr
          exact hbr
        · by_cases hBK : canonicalBKinkRegion θ s h
          · exact False.elim (hNBK hBK)
          · have hex := canonicalDeviation_regions_exhaustive θ s h
            rcases hex with hAM' | hAK' | hD' | hBK' | hBM
            · exact False.elim (hAM hAM')
            · exact False.elim (hAK hAK')
            · exact False.elim (hD hD')
            · exact False.elim (hBK hBK')
            · exact False.elim (hNBM hBM)

/-- Symmetry-labeled A-government global best-response statement. -/
theorem canonical_A_global_best_response
    {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    ∀ sA hA : ℝ, 0 ≤ sA → 0 ≤ hA →
      canonicalGovernmentDeviationWelfare θ sA hA ≤
        canonicalActiveGovernmentWelfare θ (canonicalSymmetricProfile θ) := by
  intro sA hA hs hh
  exact canonical_government_global_best_response hθ hs hh

/-- By jurisdictional symmetry, the B-government unilateral problem has the same
canonical deviation value function. -/
def canonicalBGovernmentDeviationWelfare (θ sB hB : ℝ) : ℝ :=
  canonicalGovernmentDeviationWelfare θ sB hB

theorem canonical_B_global_best_response
    {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    ∀ sB hB : ℝ, 0 ≤ sB → 0 ≤ hB →
      canonicalBGovernmentDeviationWelfare θ sB hB ≤
        canonicalActiveGovernmentWelfare θ (canonicalSymmetricProfile θ) := by
  intro sB hB hs hh
  exact canonical_government_global_best_response hθ hs hh

/-- Canonical symmetric Stage-1 policy Nash equilibrium over the full nonnegative
unilateral policy domain, after the actual piecewise Stage-2 continuation. -/
theorem canonicalSymmetricProfile_global_nash
    {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    (∀ sA hA : ℝ, 0 ≤ sA → 0 ≤ hA →
      canonicalGovernmentDeviationWelfare θ sA hA ≤
        canonicalActiveGovernmentWelfare θ (canonicalSymmetricProfile θ)) ∧
    (∀ sB hB : ℝ, 0 ≤ sB → 0 ≤ hB →
      canonicalBGovernmentDeviationWelfare θ sB hB ≤
        canonicalActiveGovernmentWelfare θ (canonicalSymmetricProfile θ)) := by
  exact ⟨canonical_A_global_best_response hθ, canonical_B_global_best_response hθ⟩

end SLGPC
