import StrategicLocalGreenPolicyCompetition.GovernmentBestResponse
import StrategicLocalGreenPolicyCompetition.Stage2OptimizationBridge

noncomputable section

open Set

namespace SLGPC

set_option maxRecDepth 100000

/-- Exact denominator of the symmetric canonical policy solution generated by the
active government FOCs. -/
def canonicalSymmetricDen (θ : ℝ) : ℝ :=
  48460000 * θ ^ 9 + 35591750 * θ ^ 8 - 695419750 * θ ^ 7 -
    511735300 * θ ^ 6 + 3553958735 * θ ^ 5 + 2526097963 * θ ^ 4 -
    7514464680 * θ ^ 3 - 5722164184 * θ ^ 2 + 5295622960 * θ +
    5650236328

def canonicalSymmetricSNum (θ : ℝ) : ℝ :=
  3946250 * θ ^ 8 - 206250 * θ ^ 7 - 55175500 * θ ^ 6 +
    2231625 * θ ^ 5 + 272035165 * θ ^ 4 - 7953000 * θ ^ 3 -
    558142864 * θ ^ 2 + 9306000 * θ + 397229536

def canonicalSymmetricHNum (θ : ℝ) : ℝ :=
  301250 * θ ^ 8 - 235250 * θ ^ 7 - 4489100 * θ ^ 6 +
    2545405 * θ ^ 5 + 24301481 * θ ^ 4 - 9071240 * θ ^ 3 -
    52368928 * θ ^ 2 + 10614480 * θ + 33055176

def canonicalSymmetricDenBernstein (θ : ℝ) : ℝ :=
  711929777328 * (1 - θ) ^ 9 +
    7074616488912 * θ * (1 - θ) ^ 8 +
    30246467240304 * θ ^ 2 * (1 - θ) ^ 7 +
    72491287738464 * θ ^ 3 * (1 - θ) ^ 6 +
    106565574163482 * θ ^ 4 * (1 - θ) ^ 5 +
    99012704671188 * θ ^ 5 * (1 - θ) ^ 4 +
    57906421844292 * θ ^ 6 * (1 - θ) ^ 3 +
    20557862515764 * θ ^ 7 * (1 - θ) ^ 2 +
    4035911590494 * θ ^ 8 * (1 - θ) +
    335939161572 * θ ^ 9

def canonicalSymmetricSNumBernstein (θ : ℝ) : ℝ :=
  22244854016 * (1 - θ) ^ 8 +
    178479968128 * θ * (1 - θ) ^ 7 +
    595247864064 * θ ^ 2 * (1 - θ) ^ 6 +
    1068674310592 * θ ^ 3 * (1 - θ) ^ 5 +
    1119546664600 * θ ^ 4 * (1 - θ) ^ 4 +
    695438745176 * θ ^ 5 * (1 - θ) ^ 3 +
    249194983128 * θ ^ 6 * (1 - θ) ^ 2 +
    46963525784 * θ ^ 7 * (1 - θ) +
    3543173872 * θ ^ 8

def canonicalSymmetricHNumBernstein (θ : ℝ) : ℝ :=
  9255449280 * (1 - θ) ^ 8 +
    77015648640 * θ * (1 - θ) ^ 7 +
    265293660800 * θ ^ 2 * (1 - θ) ^ 6 +
    490198555840 * θ ^ 3 * (1 - θ) ^ 5 +
    526058534680 * θ ^ 4 * (1 - θ) ^ 4 +
    331591967000 * θ ^ 5 * (1 - θ) ^ 3 +
    117924432920 * θ ^ 6 * (1 - θ) ^ 2 +
    20944472920 * θ ^ 7 * (1 - θ) +
    1302916720 * θ ^ 8

lemma canonicalSymmetricDen_scaled (θ : ℝ) :
    126 * canonicalSymmetricDen θ = canonicalSymmetricDenBernstein θ := by
  unfold canonicalSymmetricDen canonicalSymmetricDenBernstein
  ring

lemma canonicalSymmetricSNum_scaled (θ : ℝ) :
    56 * canonicalSymmetricSNum θ = canonicalSymmetricSNumBernstein θ := by
  unfold canonicalSymmetricSNum canonicalSymmetricSNumBernstein
  ring

lemma canonicalSymmetricHNum_scaled (θ : ℝ) :
    280 * canonicalSymmetricHNum θ = canonicalSymmetricHNumBernstein θ := by
  unfold canonicalSymmetricHNum canonicalSymmetricHNumBernstein
  ring

private lemma canonicalPositiveBase {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1)
    (hneq : θ ≠ 1) : 0 < 1 - θ := by
  exact sub_pos.mpr (lt_of_le_of_ne hθ.2 hneq)

theorem canonicalSymmetricDen_pos {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    0 < canonicalSymmetricDen θ := by
  by_cases h1 : θ = 1
  · subst θ
    norm_num [canonicalSymmetricDen]
  · have hθ0 : 0 ≤ θ := hθ.1
    have hbase : 0 < 1 - θ := canonicalPositiveBase hθ h1
    have h0 : 0 < 711929777328 * (1 - θ) ^ 9 := by positivity
    have h1n : 0 ≤ 7074616488912 * θ * (1 - θ) ^ 8 := by positivity
    have h2n : 0 ≤ 30246467240304 * θ ^ 2 * (1 - θ) ^ 7 := by positivity
    have h3n : 0 ≤ 72491287738464 * θ ^ 3 * (1 - θ) ^ 6 := by positivity
    have h4n : 0 ≤ 106565574163482 * θ ^ 4 * (1 - θ) ^ 5 := by positivity
    have h5n : 0 ≤ 99012704671188 * θ ^ 5 * (1 - θ) ^ 4 := by positivity
    have h6n : 0 ≤ 57906421844292 * θ ^ 6 * (1 - θ) ^ 3 := by positivity
    have h7n : 0 ≤ 20557862515764 * θ ^ 7 * (1 - θ) ^ 2 := by positivity
    have h8n : 0 ≤ 4035911590494 * θ ^ 8 * (1 - θ) := by positivity
    have h9n : 0 ≤ 335939161572 * θ ^ 9 := by positivity
    have hb : 0 < canonicalSymmetricDenBernstein θ := by
      unfold canonicalSymmetricDenBernstein
      nlinarith
    have hs := canonicalSymmetricDen_scaled θ
    nlinarith

theorem canonicalSymmetricSNum_pos {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    0 < canonicalSymmetricSNum θ := by
  by_cases h1 : θ = 1
  · subst θ
    norm_num [canonicalSymmetricSNum]
  · have hθ0 : 0 ≤ θ := hθ.1
    have hbase : 0 < 1 - θ := canonicalPositiveBase hθ h1
    have h0 : 0 < 22244854016 * (1 - θ) ^ 8 := by positivity
    have h1n : 0 ≤ 178479968128 * θ * (1 - θ) ^ 7 := by positivity
    have h2n : 0 ≤ 595247864064 * θ ^ 2 * (1 - θ) ^ 6 := by positivity
    have h3n : 0 ≤ 1068674310592 * θ ^ 3 * (1 - θ) ^ 5 := by positivity
    have h4n : 0 ≤ 1119546664600 * θ ^ 4 * (1 - θ) ^ 4 := by positivity
    have h5n : 0 ≤ 695438745176 * θ ^ 5 * (1 - θ) ^ 3 := by positivity
    have h6n : 0 ≤ 249194983128 * θ ^ 6 * (1 - θ) ^ 2 := by positivity
    have h7n : 0 ≤ 46963525784 * θ ^ 7 * (1 - θ) := by positivity
    have h8n : 0 ≤ 3543173872 * θ ^ 8 := by positivity
    have hb : 0 < canonicalSymmetricSNumBernstein θ := by
      unfold canonicalSymmetricSNumBernstein
      nlinarith
    have hs := canonicalSymmetricSNum_scaled θ
    nlinarith

theorem canonicalSymmetricHNum_pos {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    0 < canonicalSymmetricHNum θ := by
  by_cases h1 : θ = 1
  · subst θ
    norm_num [canonicalSymmetricHNum]
  · have hθ0 : 0 ≤ θ := hθ.1
    have hbase : 0 < 1 - θ := canonicalPositiveBase hθ h1
    have h0 : 0 < 9255449280 * (1 - θ) ^ 8 := by positivity
    have h1n : 0 ≤ 77015648640 * θ * (1 - θ) ^ 7 := by positivity
    have h2n : 0 ≤ 265293660800 * θ ^ 2 * (1 - θ) ^ 6 := by positivity
    have h3n : 0 ≤ 490198555840 * θ ^ 3 * (1 - θ) ^ 5 := by positivity
    have h4n : 0 ≤ 526058534680 * θ ^ 4 * (1 - θ) ^ 4 := by positivity
    have h5n : 0 ≤ 331591967000 * θ ^ 5 * (1 - θ) ^ 3 := by positivity
    have h6n : 0 ≤ 117924432920 * θ ^ 6 * (1 - θ) ^ 2 := by positivity
    have h7n : 0 ≤ 20944472920 * θ ^ 7 * (1 - θ) := by positivity
    have h8n : 0 ≤ 1302916720 * θ ^ 8 := by positivity
    have hb : 0 < canonicalSymmetricHNumBernstein θ := by
      unfold canonicalSymmetricHNumBernstein
      nlinarith
    have hs := canonicalSymmetricHNum_scaled θ
    nlinarith

def canonicalSymmetricS (θ : ℝ) : ℝ :=
  72 * canonicalSymmetricSNum θ / canonicalSymmetricDen θ

def canonicalSymmetricH (θ : ℝ) : ℝ :=
  300 * canonicalSymmetricHNum θ / canonicalSymmetricDen θ

def canonicalSymmetricProfile (θ : ℝ) : PolicyProfile :=
  { sA := canonicalSymmetricS θ
    hA := canonicalSymmetricH θ
    sB := canonicalSymmetricS θ
    hB := canonicalSymmetricH θ }

theorem canonicalSymmetricPolicies_pos {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    0 < canonicalSymmetricS θ ∧ 0 < canonicalSymmetricH θ := by
  constructor
  · exact div_pos (mul_pos (by norm_num) (canonicalSymmetricSNum_pos hθ))
      (canonicalSymmetricDen_pos hθ)
  · exact div_pos (mul_pos (by norm_num) (canonicalSymmetricHNum_pos hθ))
      (canonicalSymmetricDen_pos hθ)

def canonicalSymmetricW (θ : ℝ) : ℝ :=
  reducedW 2 18 (9 / 10 : ℝ) (6 / 5 : ℝ)
    (canonicalSymmetricS θ) (canonicalSymmetricH θ)

lemma canonicalInvestmentR : investmentR 4 18 (9 / 10 : ℝ) = 59 / 200 := by
  norm_num [investmentR]

lemma canonicalMonopolyM : monopolyM (investmentR 4 18 (9 / 10 : ℝ)) = 341 / 200 := by
  rw [canonicalInvestmentR]
  norm_num [monopolyM]

theorem canonicalSymmetricW_pos {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    0 < canonicalSymmetricW θ := by
  rcases canonicalSymmetricPolicies_pos hθ with ⟨hs, hh⟩
  unfold canonicalSymmetricW reducedW policyY
  nlinarith

/-- The extra denominator generated by `q0=m/(L+theta)` is positive on `[0,1]`. -/
lemma canonicalQ0DenPoly_pos {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    0 < 341 + 200 * θ - 100 * θ ^ 2 - 50 * θ ^ 3 := by
  have hsq : θ ^ 2 ≤ 1 := by
    nlinarith [mul_nonneg hθ.1 (sub_nonneg.mpr hθ.2)]
  have hcub : θ ^ 3 ≤ 1 := by
    have hnonneg : 0 ≤ θ ^ 2 * (1 - θ) :=
      mul_nonneg (sq_nonneg θ) (sub_nonneg.mpr hθ.2)
    nlinarith
  nlinarith [hθ.1]

/-- The exact rational symmetric policy formulas solve both canonical active
Stage-1 government FOCs. -/
theorem canonicalSymmetricProfile_FOCs
    {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    canonicalActiveGovernmentGradient θ (canonicalSymmetricProfile θ) .sA = 0 ∧
    canonicalActiveGovernmentGradient θ (canonicalSymmetricProfile θ) .hA = 0 := by
  have hD : cournotD θ ≠ 0 := (cournotD_pos hθ).ne'
  have hred : canonicalReducedDetNumerator θ ≠ 0 :=
    (canonicalReducedDetNumerator_pos hθ).ne'
  have hden : canonicalSymmetricDen θ ≠ 0 :=
    (canonicalSymmetricDen_pos hθ).ne'
  have hq0 : 341 + 200 * θ - 100 * θ ^ 2 - 50 * θ ^ 3 ≠ 0 :=
    (canonicalQ0DenPoly_pos hθ).ne'
  constructor
  · unfold canonicalActiveGovernmentGradient modelGovernmentGradient
      canonicalSymmetricProfile canonicalSymmetricS canonicalSymmetricH
      interiorPolicyQA interiorPolicyQB qASlope qBSlope ownSubsidySlope
      ownInfrastructureSlope policyY governmentDirectionalGradient
      reducedEmissions reducedEmissionsSlope
    rw [canonicalT0_closed hθ, canonicalT1_closed hθ, canonicalL_closed hθ,
      canonicalChiG_closed, canonicalRho_closed]
    unfold reducedQ0
    field_simp [hD, hred, hden, hq0]
    unfold canonicalSymmetricDen canonicalSymmetricSNum canonicalSymmetricHNum
      canonicalReducedDetNumerator cournotD
    ring
  · unfold canonicalActiveGovernmentGradient modelGovernmentGradient
      canonicalSymmetricProfile canonicalSymmetricS canonicalSymmetricH
      interiorPolicyQA interiorPolicyQB qASlope qBSlope ownSubsidySlope
      ownInfrastructureSlope policyY governmentDirectionalGradient
      reducedEmissions reducedEmissionsSlope
    rw [canonicalT0_closed hθ, canonicalT1_closed hθ, canonicalL_closed hθ,
      canonicalChiG_closed, canonicalRho_closed]
    unfold reducedQ0
    field_simp [hD, hred, hden, hq0]
    unfold canonicalSymmetricDen canonicalSymmetricSNum canonicalSymmetricHNum
      canonicalReducedDetNumerator cournotD
    ring

theorem canonicalSymmetricProfile_active_best_response
    {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) (ds dh : ℝ) :
    canonicalActiveGovernmentWelfare θ
        (ownPolicyShift (canonicalSymmetricProfile θ) ds dh) ≤
      canonicalActiveGovernmentWelfare θ (canonicalSymmetricProfile θ) := by
  rcases canonicalSymmetricProfile_FOCs hθ with ⟨hs, hh⟩
  exact canonicalActiveGovernment_best_response hθ hs hh ds dh

theorem canonicalSymmetricProfile_duopoly
    {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    duopolyRegion (canonicalL θ) θ
      (canonicalSymmetricW θ) (canonicalSymmetricW θ) := by
  have hR : investmentR 4 18 (9 / 10 : ℝ) < (3 / 4 : ℝ) := by
    rw [canonicalInvestmentR]
    norm_num
  have hL : θ < canonicalL θ := reducedL_gt_theta hθ hR
  have hw := canonicalSymmetricW_pos hθ
  constructor <;> nlinarith

/-- Polynomial certificate that nonnegative own policies cannot enter the
rival-dominance side against the symmetric canonical rival. -/
def canonicalLowerMarginPoly (θ : ℝ) : ℝ :=
  2423000000 * θ ^ 12 - 50157975000 * θ ^ 10 - 4271625000 * θ ^ 9 +
    411744944750 * θ ^ 8 + 60785223750 * θ ^ 7 - 1688421409600 * θ ^ 6 -
    322320590325 * θ ^ 5 + 3627085487783 * θ ^ 4 + 754409982600 * θ ^ 3 -
    3960877651544 * θ ^ 2 - 657228805200 * θ + 1926730587848

def canonicalLowerMarginBernstein (θ : ℝ) : ℝ :=
  1926730587848 * (1 - θ) ^ 12 +
    22463538248976 * θ * (1 - θ) ^ 11 +
    115973824289224 * θ ^ 2 * (1 - θ) ^ 10 +
    348878778507720 * θ ^ 3 * (1 - θ) ^ 9 +
    677466169138463 * θ ^ 4 * (1 - θ) ^ 8 +
    889632924359875 * θ ^ 5 * (1 - θ) ^ 7 +
    805859214999361 * θ ^ 6 * (1 - θ) ^ 6 +
    505523718876901 * θ ^ 7 * (1 - θ) ^ 5 +
    218121599655055 * θ ^ 8 * (1 - θ) ^ 4 +
    63820795675653 * θ ^ 9 * (1 - θ) ^ 3 +
    12414588739187 * θ ^ 10 * (1 - θ) ^ 2 +
    1539849910075 * θ ^ 11 * (1 - θ) +
    99901170062 * θ ^ 12

lemma canonicalLowerMargin_bernstein (θ : ℝ) :
    canonicalLowerMarginPoly θ = canonicalLowerMarginBernstein θ := by
  unfold canonicalLowerMarginPoly canonicalLowerMarginBernstein
  ring

theorem canonicalLowerMarginPoly_pos {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    0 < canonicalLowerMarginPoly θ := by
  by_cases h1 : θ = 1
  · subst θ
    norm_num [canonicalLowerMarginPoly]
  · have hθ0 : 0 ≤ θ := hθ.1
    have hbase : 0 < 1 - θ := canonicalPositiveBase hθ h1
    have h0 : 0 < 1926730587848 * (1 - θ) ^ 12 := by positivity
    have h1n : 0 ≤ 22463538248976 * θ * (1 - θ) ^ 11 := by positivity
    have h2n : 0 ≤ 115973824289224 * θ ^ 2 * (1 - θ) ^ 10 := by positivity
    have h3n : 0 ≤ 348878778507720 * θ ^ 3 * (1 - θ) ^ 9 := by positivity
    have h4n : 0 ≤ 677466169138463 * θ ^ 4 * (1 - θ) ^ 8 := by positivity
    have h5n : 0 ≤ 889632924359875 * θ ^ 5 * (1 - θ) ^ 7 := by positivity
    have h6n : 0 ≤ 805859214999361 * θ ^ 6 * (1 - θ) ^ 6 := by positivity
    have h7n : 0 ≤ 505523718876901 * θ ^ 7 * (1 - θ) ^ 5 := by positivity
    have h8n : 0 ≤ 218121599655055 * θ ^ 8 * (1 - θ) ^ 4 := by positivity
    have h9n : 0 ≤ 63820795675653 * θ ^ 9 * (1 - θ) ^ 3 := by positivity
    have h10n : 0 ≤ 12414588739187 * θ ^ 10 * (1 - θ) ^ 2 := by positivity
    have h11n : 0 ≤ 1539849910075 * θ ^ 11 * (1 - θ) := by positivity
    have h12n : 0 ≤ 99901170062 * θ ^ 12 := by positivity
    rw [canonicalLowerMargin_bernstein]
    unfold canonicalLowerMarginBernstein
    nlinarith

end SLGPC
