import StrategicLocalGreenPolicyCompetition.GovernmentBestResponse
import StrategicLocalGreenPolicyCompetition.Stage2OptimizationBridge

noncomputable section

open Set

namespace SLGPC

set_option maxRecDepth 100000

/-- Exact denominator of the symmetric canonical policy solution generated by the
active government FOCs. -/
def canonicalSymmetricDen (θ : ℝ) : ℝ :=
  48460000 * θ ^ 9 + 35591750 * θ ^ 8 - 695419750 * θ ^ 7 -
    511735300 * θ ^ 6 + 3553958735 * θ ^ 5 + 2526097963 * θ ^ 4 -
    7514464680 * θ ^ 3 - 5722164184 * θ ^ 2 + 5295622960 * θ +
    5650236328

/-- Numerator of the symmetric subsidy. -/
def canonicalSymmetricSNum (θ : ℝ) : ℝ :=
  3946250 * θ ^ 8 - 206250 * θ ^ 7 - 55175500 * θ ^ 6 +
    2231625 * θ ^ 5 + 272035165 * θ ^ 4 - 7953000 * θ ^ 3 -
    558142864 * θ ^ 2 + 9306000 * θ + 397229536

/-- Numerator of the symmetric infrastructure choice. -/
def canonicalSymmetricHNum (θ : ℝ) : ℝ :=
  301250 * θ ^ 8 - 235250 * θ ^ 7 - 4489100 * θ ^ 6 +
    2545405 * θ ^ 5 + 24301481 * θ ^ 4 - 9071240 * θ ^ 3 -
    52368928 * θ ^ 2 + 10614480 * θ + 33055176

/-- Positive Bernstein certificate for `126 * canonicalSymmetricDen`. -/
def canonicalSymmetricDenBernstein (θ : ℝ) : ℝ :=
  711929777328 * (1 - θ) ^ 9 +
    7074616488912 * θ * (1 - θ) ^ 8 +
    30246467240304 * θ ^ 2 * (1 - θ) ^ 7 +
    72491287738464 * θ ^ 3 * (1 - θ) ^ 6 +
    106565574163482 * θ ^ 4 * (1 - θ) ^ 5 +
    99012704671188 * θ ^ 5 * (1 - θ) ^ 4 +
    57906421844292 * θ ^ 6 * (1 - θ) ^ 3 +
    20557862515764 * θ ^ 7 * (1 - θ) ^ 2 +
    4035911590494 * θ ^ 8 * (1 - θ) +
    335939161572 * θ ^ 9

/-- Positive Bernstein certificate for `56 * canonicalSymmetricSNum`. -/
def canonicalSymmetricSNumBernstein (θ : ℝ) : ℝ :=
  22244854016 * (1 - θ) ^ 8 +
    178479968128 * θ * (1 - θ) ^ 7 +
    595247864064 * θ ^ 2 * (1 - θ) ^ 6 +
    1068674310592 * θ ^ 3 * (1 - θ) ^ 5 +
    1119546664600 * θ ^ 4 * (1 - θ) ^ 4 +
    695438745176 * θ ^ 5 * (1 - θ) ^ 3 +
    249194983128 * θ ^ 6 * (1 - θ) ^ 2 +
    46963525784 * θ ^ 7 * (1 - θ) +
    3543173872 * θ ^ 8

/-- Positive Bernstein certificate for `280 * canonicalSymmetricHNum`. -/
def canonicalSymmetricHNumBernstein (θ : ℝ) : ℝ :=
  9255449280 * (1 - θ) ^ 8 +
    77015648640 * θ * (1 - θ) ^ 7 +
    265293660800 * θ ^ 2 * (1 - θ) ^ 6 +
    490198555840 * θ ^ 3 * (1 - θ) ^ 5 +
    526058534680 * θ ^ 4 * (1 - θ) ^ 4 +
    331591967000 * θ ^ 5 * (1 - θ) ^ 3 +
    117924432920 * θ ^ 6 * (1 - θ) ^ 2 +
    20944472920 * θ ^ 7 * (1 - θ) +
    1302916720 * θ ^ 8

lemma canonicalSymmetricDen_scaled (θ : ℝ) :
    126 * canonicalSymmetricDen θ = canonicalSymmetricDenBernstein θ := by
  unfold canonicalSymmetricDen canonicalSymmetricDenBernstein
  ring

lemma canonicalSymmetricSNum_scaled (θ : ℝ) :
    56 * canonicalSymmetricSNum θ = canonicalSymmetricSNumBernstein θ := by
  unfold canonicalSymmetricSNum canonicalSymmetricSNumBernstein
  ring

lemma canonicalSymmetricHNum_scaled (θ : ℝ) :
    280 * canonicalSymmetricHNum θ = canonicalSymmetricHNumBernstein θ := by
  unfold canonicalSymmetricHNum canonicalSymmetricHNumBernstein
  ring

private lemma positive_bernstein_base {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1)
    (hneq : θ ≠ 1) : 0 < 1 - θ := by
  exact sub_pos.mpr (lt_of_le_of_ne hθ.2 hneq)

/-- The symmetric-policy denominator is positive on the full rivalry interval. -/
theorem canonicalSymmetricDen_pos {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    0 < canonicalSymmetricDen θ := by
  by_cases h1 : θ = 1
  · subst θ
    norm_num [canonicalSymmetricDen]
  · have hbase := positive_bernstein_base hθ h1
    have hb : 0 < canonicalSymmetricDenBernstein θ := by
      unfold canonicalSymmetricDenBernstein
      positivity
    have hs := canonicalSymmetricDen_scaled θ
    nlinarith

/-- The symmetric subsidy numerator is positive on `[0,1]`. -/
theorem canonicalSymmetricSNum_pos {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    0 < canonicalSymmetricSNum θ := by
  by_cases h1 : θ = 1
  · subst θ
    norm_num [canonicalSymmetricSNum]
  · have hbase := positive_bernstein_base hθ h1
    have hb : 0 < canonicalSymmetricSNumBernstein θ := by
      unfold canonicalSymmetricSNumBernstein
      positivity
    have hs := canonicalSymmetricSNum_scaled θ
    nlinarith

/-- The symmetric infrastructure numerator is positive on `[0,1]`. -/
theorem canonicalSymmetricHNum_pos {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    0 < canonicalSymmetricHNum θ := by
  by_cases h1 : θ = 1
  · subst θ
    norm_num [canonicalSymmetricHNum]
  · have hbase := positive_bernstein_base hθ h1
    have hb : 0 < canonicalSymmetricHNumBernstein θ := by
      unfold canonicalSymmetricHNumBernstein
      positivity
    have hs := canonicalSymmetricHNum_scaled θ
    nlinarith

/-- Symmetric canonical Stage-1 subsidy. -/
def canonicalSymmetricS (θ : ℝ) : ℝ :=
  72 * canonicalSymmetricSNum θ / canonicalSymmetricDen θ

/-- Symmetric canonical Stage-1 infrastructure. -/
def canonicalSymmetricH (θ : ℝ) : ℝ :=
  300 * canonicalSymmetricHNum θ / canonicalSymmetricDen θ

/-- Symmetric canonical policy profile. -/
def canonicalSymmetricProfile (θ : ℝ) : PolicyProfile :=
  { sA := canonicalSymmetricS θ
    hA := canonicalSymmetricH θ
    sB := canonicalSymmetricS θ
    hB := canonicalSymmetricH θ }

/-- The canonical equilibrium policies satisfy the nonnegativity constraints
strictly throughout `[0,1]`. -/
theorem canonicalSymmetricPolicies_pos {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    0 < canonicalSymmetricS θ ∧ 0 < canonicalSymmetricH θ := by
  constructor
  · exact div_pos (mul_pos (by norm_num) (canonicalSymmetricSNum_pos hθ))
      (canonicalSymmetricDen_pos hθ)
  · exact div_pos (mul_pos (by norm_num) (canonicalSymmetricHNum_pos hθ))
      (canonicalSymmetricDen_pos hθ)

/-- Canonical reduced intercept attached to one symmetric government. -/
def canonicalSymmetricW (θ : ℝ) : ℝ :=
  reducedW 2 18 (9 / 10 : ℝ) (6 / 5 : ℝ)
    (canonicalSymmetricS θ) (canonicalSymmetricH θ)

lemma canonicalInvestmentR : investmentR 4 18 (9 / 10 : ℝ) = 59 / 200 := by
  norm_num [investmentR]

lemma canonicalMonopolyM : monopolyM (investmentR 4 18 (9 / 10 : ℝ)) = 341 / 200 := by
  rw [canonicalInvestmentR]
  norm_num [monopolyM]

/-- The symmetric reduced intercept is strictly positive. -/
theorem canonicalSymmetricW_pos {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    0 < canonicalSymmetricW θ := by
  rcases canonicalSymmetricPolicies_pos hθ with ⟨hs, hh⟩
  unfold canonicalSymmetricW reducedW policyY
  nlinarith

/-- The exact rational symmetric policy formulas solve both canonical active
Stage-1 government FOCs. -/
theorem canonicalSymmetricProfile_FOCs
    {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    canonicalActiveGovernmentGradient θ (canonicalSymmetricProfile θ) .sA = 0 ∧
    canonicalActiveGovernmentGradient θ (canonicalSymmetricProfile θ) .hA = 0 := by
  have hD : cournotD θ ≠ 0 := (cournotD_pos hθ).ne'
  have hred : canonicalReducedDetNumerator θ ≠ 0 :=
    (canonicalReducedDetNumerator_pos hθ).ne'
  have hden : canonicalSymmetricDen θ ≠ 0 :=
    (canonicalSymmetricDen_pos hθ).ne'
  constructor
  · unfold canonicalActiveGovernmentGradient modelGovernmentGradient
      canonicalSymmetricProfile canonicalSymmetricS canonicalSymmetricH
      interiorPolicyQA interiorPolicyQB qASlope qBSlope ownSubsidySlope
      ownInfrastructureSlope policyY governmentDirectionalGradient
      reducedEmissions reducedEmissionsSlope
    rw [canonicalL_closed hθ, canonicalT0_closed hθ, canonicalT1_closed hθ,
      canonicalChiG_closed, canonicalRho_closed]
    unfold reducedQ0
    field_simp [hD, hred, hden]
    unfold canonicalSymmetricDen canonicalSymmetricSNum canonicalSymmetricHNum
      canonicalReducedDetNumerator cournotD
    ring
  · unfold canonicalActiveGovernmentGradient modelGovernmentGradient
      canonicalSymmetricProfile canonicalSymmetricS canonicalSymmetricH
      interiorPolicyQA interiorPolicyQB qASlope qBSlope ownSubsidySlope
      ownInfrastructureSlope policyY governmentDirectionalGradient
      reducedEmissions reducedEmissionsSlope
    rw [canonicalL_closed hθ, canonicalT0_closed hθ, canonicalT1_closed hθ,
      canonicalChiG_closed, canonicalRho_closed]
    unfold reducedQ0
    field_simp [hD, hred, hden]
    unfold canonicalSymmetricDen canonicalSymmetricSNum canonicalSymmetricHNum
      canonicalReducedDetNumerator cournotD
    ring

/-- The symmetric policy profile is a strict global maximizer of the active
quadratic government branch against the symmetric rival policy. -/
theorem canonicalSymmetricProfile_active_best_response
    {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) (ds dh : ℝ) :
    canonicalActiveGovernmentWelfare θ
        (ownPolicyShift (canonicalSymmetricProfile θ) ds dh) ≤
      canonicalActiveGovernmentWelfare θ (canonicalSymmetricProfile θ) := by
  rcases canonicalSymmetricProfile_FOCs hθ with ⟨hs, hh⟩
  exact canonicalActiveGovernment_best_response hθ hs hh ds dh

/-- Symmetry together with `R<3/4` places the canonical policy profile strictly
inside the active-duopoly Stage-2 region. -/
theorem canonicalSymmetricProfile_duopoly
    {θ : ℝ} (hθ : θ ∈ Icc (0 : ℝ) 1) :
    duopolyRegion (canonicalL θ) θ
      (canonicalSymmetricW θ) (canonicalSymmetricW θ) := by
  have hR : investmentR 4 18 (9 / 10 : ℝ) < (3 / 4 : ℝ) := by
    rw [canonicalInvestmentR]
    norm_num
  have hL : θ < canonicalL θ := by
    exact reducedL_gt_theta hθ hR
  have hw := canonicalSymmetricW_pos hθ
  constructor <;> nlinarith

end SLGPC
