import StrategicLocalGreenPolicyCompetition.GovernmentStage

noncomputable section

namespace SLGPC

/-- Stage-1 policy profile in the manuscript ordering `(s_A,h_A,s_B,h_B)`. -/
structure PolicyProfile where
  sA : ℝ
  hA : ℝ
  sB : ℝ
  hB : ℝ

/-- Shift one policy coordinate by an arbitrary scalar amount. -/
def shiftPolicy (z : PolicyProfile) (i : PolicyCoord) (t : ℝ) : PolicyProfile :=
  match i with
  | .sA => { z with sA := z.sA + t }
  | .hA => { z with hA := z.hA + t }
  | .sB => { z with sB := z.sB + t }
  | .hB => { z with hB := z.hB + t }

/-- Firm A's affine interior quantity as a function of the four Stage-1 policies. -/
def interiorPolicyQA
    (m kg μ ν L θ : ℝ) (z : PolicyProfile) : ℝ :=
  reducedQ0 m L θ +
    reducedT0 L θ * policyY kg μ ν z.sA z.hA +
    reducedT1 L θ * policyY kg μ ν z.sB z.hB

/-- Firm B's affine interior quantity, with own/rival loadings interchanged. -/
def interiorPolicyQB
    (m kg μ ν L θ : ℝ) (z : PolicyProfile) : ℝ :=
  reducedQ0 m L θ +
    reducedT1 L θ * policyY kg μ ν z.sA z.hA +
    reducedT0 L θ * policyY kg μ ν z.sB z.hB

/-- The `qASlope` vector is exactly the coefficient generated by shifting any one
policy coordinate in the Phase-3 affine quantity representation. -/
theorem interiorPolicyQA_shift
    {m kg μ ν L θ t : ℝ} {z : PolicyProfile} (i : PolicyCoord) :
    interiorPolicyQA m kg μ ν L θ (shiftPolicy z i t) =
      interiorPolicyQA m kg μ ν L θ z + t * qASlope kg μ ν L θ i := by
  cases i <;> simp [shiftPolicy, interiorPolicyQA, qASlope, policyY] <;> ring

/-- Symmetric provenance certificate for the `qBSlope` vector. -/
theorem interiorPolicyQB_shift
    {m kg μ ν L θ t : ℝ} {z : PolicyProfile} (i : PolicyCoord) :
    interiorPolicyQB m kg μ ν L θ (shiftPolicy z i t) =
      interiorPolicyQB m kg μ ν L θ z + t * qBSlope kg μ ν L θ i := by
  cases i <;> simp [shiftPolicy, interiorPolicyQB, qBSlope, policyY] <;> ring

/-- Direct own-subsidy coordinate slope under a generic policy shift. -/
theorem shiftPolicy_sA
    {z : PolicyProfile} {t : ℝ} (i : PolicyCoord) :
    (shiftPolicy z i t).sA = z.sA + t * ownSubsidySlope i := by
  cases i <;> simp [shiftPolicy, ownSubsidySlope]

/-- Direct own-infrastructure coordinate slope under a generic policy shift. -/
theorem shiftPolicy_hA
    {z : PolicyProfile} {t : ℝ} (i : PolicyCoord) :
    (shiftPolicy z i t).hA = z.hA + t * ownInfrastructureSlope i := by
  cases i <;> simp [shiftPolicy, ownInfrastructureSlope]

lemma interiorPolicyQA_shift_two
    {m kg μ ν L θ t r : ℝ} {z : PolicyProfile} (i j : PolicyCoord) :
    interiorPolicyQA m kg μ ν L θ (shiftPolicy (shiftPolicy z i t) j r) =
      interiorPolicyQA m kg μ ν L θ z +
        t * qASlope kg μ ν L θ i + r * qASlope kg μ ν L θ j := by
  rw [interiorPolicyQA_shift, interiorPolicyQA_shift]

lemma interiorPolicyQB_shift_two
    {m kg μ ν L θ t r : ℝ} {z : PolicyProfile} (i j : PolicyCoord) :
    interiorPolicyQB m kg μ ν L θ (shiftPolicy (shiftPolicy z i t) j r) =
      interiorPolicyQB m kg μ ν L θ z +
        t * qBSlope kg μ ν L θ i + r * qBSlope kg μ ν L θ j := by
  rw [interiorPolicyQB_shift, interiorPolicyQB_shift]

lemma shiftPolicy_sA_two
    {z : PolicyProfile} {t r : ℝ} (i j : PolicyCoord) :
    (shiftPolicy (shiftPolicy z i t) j r).sA =
      z.sA + t * ownSubsidySlope i + r * ownSubsidySlope j := by
  rw [shiftPolicy_sA, shiftPolicy_sA]

lemma shiftPolicy_hA_two
    {z : PolicyProfile} {t r : ℝ} (i j : PolicyCoord) :
    (shiftPolicy (shiftPolicy z i t) j r).hA =
      z.hA + t * ownInfrastructureSlope i + r * ownInfrastructureSlope j := by
  rw [shiftPolicy_hA, shiftPolicy_hA]

/-- Reduced active-duopoly government welfare as an actual function of the Stage-1
policy profile, with Phase-3 affine firm quantities substituted. -/
def interiorReducedGovernmentPolicyWelfare
    (kx kg μ ν κ d e β ξ Ebar m L θ : ℝ) (z : PolicyProfile) : ℝ :=
  reducedGovernmentWelfare θ (producerRho kx kg μ θ) (interiorChiG kg μ θ)
    kg κ d e β ξ Ebar
    (interiorPolicyQA m kg μ ν L θ z)
    (interiorPolicyQB m kg μ ν L θ z) z.sA z.hA

/-- The same policy objective written on the active primitive-welfare side, before
using the Phase-6 government reduction theorem. -/
def interiorActiveGovernmentPolicyWelfare
    (kx kg μ ν κ d e β ξ Ebar m L θ : ℝ) (z : PolicyProfile) : ℝ :=
  let qA := interiorPolicyQA m kg μ ν L θ z
  let qB := interiorPolicyQB m kg μ ν L θ z
  activeGovernmentWelfare kx kg κ d e β ξ Ebar θ qA qB
    (interiorX kx θ qA) (interiorG kg μ z.sA θ qA) z.sA z.hA

/-- The active primitive policy objective and the reduced policy objective coincide. -/
theorem interiorActiveGovernmentPolicyWelfare_eq_reduced
    {kx kg μ ν κ d e β ξ Ebar m L θ : ℝ} {z : PolicyProfile}
    (hkg : kg ≠ 0) :
    interiorActiveGovernmentPolicyWelfare kx kg μ ν κ d e β ξ Ebar m L θ z =
      interiorReducedGovernmentPolicyWelfare kx kg μ ν κ d e β ξ Ebar m L θ z := by
  unfold interiorActiveGovernmentPolicyWelfare interiorReducedGovernmentPolicyWelfare
  exact activeGovernmentWelfare_reduction hkg

/-- The model-specialized Hessian entry is exactly the mixed second finite
difference of the reduced Stage-1 policy objective.  This links the Phase-3 affine
quantity system to the Phase-6 Hessian without an external symbolic step. -/
theorem interiorReducedGovernmentPolicyWelfare_mixed_second_difference
    {kx kg μ ν κ d e β ξ Ebar m L θ t r : ℝ}
    {z : PolicyProfile} (i j : PolicyCoord) :
    interiorReducedGovernmentPolicyWelfare kx kg μ ν κ d e β ξ Ebar m L θ
        (shiftPolicy (shiftPolicy z i t) j r) -
      interiorReducedGovernmentPolicyWelfare kx kg μ ν κ d e β ξ Ebar m L θ
        (shiftPolicy z i t) -
      interiorReducedGovernmentPolicyWelfare kx kg μ ν κ d e β ξ Ebar m L θ
        (shiftPolicy z j r) +
      interiorReducedGovernmentPolicyWelfare kx kg μ ν κ d e β ξ Ebar m L θ z =
        t * r * modelGovernmentHessianEntry kx kg μ ν κ d e β ξ L θ i j := by
  unfold interiorReducedGovernmentPolicyWelfare modelGovernmentHessianEntry
  rw [interiorPolicyQA_shift_two, interiorPolicyQB_shift_two,
      shiftPolicy_sA_two, shiftPolicy_hA_two,
      interiorPolicyQA_shift, interiorPolicyQB_shift,
      shiftPolicy_sA, shiftPolicy_hA,
      interiorPolicyQA_shift, interiorPolicyQB_shift,
      shiftPolicy_sA, shiftPolicy_hA]
  exact reducedGovernmentWelfare_mixed_second_difference

/-- Consequently the same Hessian certificate applies to the primitive active
policy objective after substituting the interior firm continuation. -/
theorem interiorActiveGovernmentPolicyWelfare_mixed_second_difference
    {kx kg μ ν κ d e β ξ Ebar m L θ t r : ℝ}
    {z : PolicyProfile} (hkg : kg ≠ 0) (i j : PolicyCoord) :
    interiorActiveGovernmentPolicyWelfare kx kg μ ν κ d e β ξ Ebar m L θ
        (shiftPolicy (shiftPolicy z i t) j r) -
      interiorActiveGovernmentPolicyWelfare kx kg μ ν κ d e β ξ Ebar m L θ
        (shiftPolicy z i t) -
      interiorActiveGovernmentPolicyWelfare kx kg μ ν κ d e β ξ Ebar m L θ
        (shiftPolicy z j r) +
      interiorActiveGovernmentPolicyWelfare kx kg μ ν κ d e β ξ Ebar m L θ z =
        t * r * modelGovernmentHessianEntry kx kg μ ν κ d e β ξ L θ i j := by
  rw [interiorActiveGovernmentPolicyWelfare_eq_reduced hkg,
      interiorActiveGovernmentPolicyWelfare_eq_reduced hkg,
      interiorActiveGovernmentPolicyWelfare_eq_reduced hkg,
      interiorActiveGovernmentPolicyWelfare_eq_reduced hkg]
  exact interiorReducedGovernmentPolicyWelfare_mixed_second_difference i j

end SLGPC
