import StrategicLocalGreenPolicyCompetition.Threshold
import StrategicLocalGreenPolicyCompetition.Proposition2
import StrategicLocalGreenPolicyCompetition.Proposition2Sign
import StrategicLocalGreenPolicyCompetition.Proposition2Theta
